### ISSUE TITLE
Disable Temporarily (e.g. 5 Minutes)

### ISSUE THREAD

**Issue by epheterson** [davidmerrique/homebridge-adguardhome#15]
Switching over from Pi-Hole to AdGuard Home, so far so good, though Pi-Hole has a "Disable Temporarily" feature which AdGuard Home is missing.

It'd be great if the toggle in HomeKit set a customizable timer within the homebridge plugin to disable for X minutes, then re-enable automatically. Usually it's only needed to be off for a few minutes to load one site.

**Comment by Delvien** [comment]
I agree, this would be a great addition to the homebridge plugin

**Comment by coalfield** [comment]
+1 here was looking on the readme for that exact thing!

**Comment by peterneutron** [comment]
@davidmerrique Sorry to ping you on this, but this functionality is now available via the API (since `0.107.28`)and would be a great addition to this plugin. See https://github.com/AdguardTeam/AdGuardHome/commit/9c48e96939c939b82a57b5c6690872faac8ded26

**Comment by dwaan** [comment]
I've update the plugin with auto on timer, but it's not based on the API, but just regular javascript timeout. It also to support older AdGuard Home version (since the docker image seems to stuck in version v0.107.16 somehow)

**Comment by cistearns** [comment]
Having an additional device for the timer is a little confusing, I understand the intent, so that one has a timer and one isn't. Maybe I'm missing something, but ideally I'd like it to only have one device added to HomeKit, the one that automatically turns AdGuard back on after a set time.  I use the HomeKit switch when I just need to turn it off for one site, and usually forget to turn it back on.

**Comment by dwaan** [comment]
> Having an additional device for the timer is a little confusing, I understand the intent, so that one has a timer and one isn't. Maybe I'm missing something, but ideally I'd like it to only have one device added to HomeKit, the one that automatically turns AdGuard back on after a set time. I use the HomeKit switch when I just need to turn it off for one site, and usually forget to turn it back on.

I see this as a non issue as you can just set one of the timer as your main device and ignore the rest. But thank you for the input, in the next update I’ll put another option to hide the non-timer device so the plug-in can output one timer device.
