### ISSUE TITLE
1.6.0 update forces use as a lock

### ISSUE THREAD

**Issue by tjcahill** [davidmerrique/homebridge-adguardhome#19]
The new update forces AdGuard Home to display as a lock exclusively, rather than allowing for the option for switch, lock, etc. 

Usage as just a lock is not ideal in some use cases because it does now allow for grouping accessories. It also breaks the existing workflow/setup in the Home app and shows that something (possibly critical) is open instead of showing a switch is on or off. 

In my use case, I run two instances of AdGuard Home on my network. Using this plugin has been awesome to manage both instances directly, instead of controlling one and waiting for this sync to take over. 

Ideal behavior for me would be to include the option of displaying as a type of accessory rather than moving to exclusive use of the lock accessory.

**Comment by elcid2012** [comment]
Agreed, this needs to be moved back to a switch. This change results in having to create two separate automations (one for control AGH when a dummy switch is turned off, and another for the dummy switch turning back on). The description for AGH now being "Locked" or "Unlocked" is ambiguous - it doesn't make any sense. This absolutely should be converted back to a switch device.

**Comment by dwaan** [comment]
Noted, will add an option to display it as switch in future release.

**Comment by tjcahill** [comment]
Looks like 1.6.1 changes the default behavior back. Much appreciated!
