### ISSUE TITLE
Update with Protection Pause

### ISSUE THREAD

**Issue by jachristian11** [davidmerrique/homebridge-adguardhome#24]
AdGuard Home [v0.107.28](https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.107.28) was just released and now supports "Global protection pause." Is would be awesome if this Homebridge plugin could be updated to take advantage of this new option.

Additional details can be found at https://github.com/AdguardTeam/AdGuardHome/issues/1333

**Comment by jachristian11** [comment]
There is a Homebridge pihole plugin (https://github.com/arendruni/homebridge-pihole#readme) that has implemented a similar auto re-enable feature that has worked great for me in the past when using pihole instead of AdGuard.

**Comment by rcoletti116** [comment]
I've been working on this in my local install. I have set it up with only the switch option (no lock). First it's a swap for the new "protection" endpoint, but this requires an extra header "duration." I can kind of get it to work, but the plugin behavior is weird. It's as if the plugin doesn't know the current or target state of the switch, which makes it impossible to supply the proper value for the duration header. If you're pausing the service you supply a time in ms (which I've made configurable from the plugin), but when unpausing (in the event you want to turn it back on before the pause is up) you have to supply duration: null.
I actually tried using two switches; one for pause and the other for normal on/off. This works, but is clunky and not ideal. Where I'd like to get to and may need @davidmerrique 's help is to have the pause duration in the plugin config. If left blank it will default to null, so the switch would operate as usual. 

I don't use the "lock" functionality, but I imagine the best scenario is for the lock and switch to have the same options.

**Comment by dwaan** [comment]
I've update the plugin with auto on timer, but it's not based on the API, but just regular javascript timeout. It also to support older AdGuard Home version (since the docker image seems to stuck in version v0.107.16 somehow)
