### ISSUE TITLE
error after installing plugin in homebridge 1.2.5

### ISSUE THREAD

**Issue by naspinec** [davidmerrique/homebridge-adguardhome#3]
After installing this plugins I got an error message :
node:1353) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'body' of undefined
    at /homebridge/node_modules/homebridge-adguardhome/src/index.ts:82:45
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1353) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1353) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

This error made the plugin inoperable.

**Comment by dekay7** [comment]
I am getting the same error :(

**Comment by davidmerrique** [comment]
@naspinec @dekay7 Try updating to the latest version. It should be fixed now.

**Comment by dekay7** [comment]
Yep! It works! Thank you so much!

**Comment by naspinec** [comment]
I have tested and it worked. Thanks a lot.
