### ISSUE TITLE
HTTPS Support

### ISSUE THREAD

**Issue by Roy-H23** [davidmerrique/homebridge-adguardhome#5]
Greetings,

My AdGuard is running on https.
But the plugin seems not to support that.
Always sends http request.

Would appreciate a fix. 
Thank you!

**Comment by davidmerrique** [comment]
@Roy-H23 Hi, give the latest version a try. I added an option to use HTTPS

**Comment by Roy-H23** [comment]
Hi David,

this was freaking fast.
But it looks like something is not working atm:
    "accessories": [
        {
            "host": "192.168.178.4",
            "https": true,
            "port": 443,
            "username": "USER",
            "password": "PW",
            "name": "AdGuard Home",
            "accessory": "AdGuardHome"
        }
        
Is there a way to debug?

**Comment by davidmerrique** [comment]
@Roy-H23 Hmm. I'll have to look into it a bit further.

Unfortunately my instance of AdGuard Home isn't running on https so I can't properly debug myself unless I get one up and running on https.

Do you see any errors in the homebridge logs?
Try the version I just pushed.

**Comment by Roy-H23** [comment]
Ha your last push fixed it.
It is working now.

Thanks for the prompt help!
